import { MonsterAbility, MonsterBodyPart, MonsterClass, MonsterShortInfo, MonsterStats, SaleInfo } from '../typings/monster';
export default class Monster {
    private id;
    private name;
    private img;
    private owner;
    private level;
    private birth_day;
    private value;
    private gene;
    private sale_info;
    private stats;
    private class;
    private abilities;
    private body;
    private children?;
    private parent?;
    private breed_count;
    constructor(id: string, name: string, img: string, owner: string, parent?: MonsterShortInfo[], stats?: MonsterStats);
    get _sale_info(): SaleInfo;
    get _id(): string;
    set _sale_info(_info: SaleInfo);
    get _value(): number;
    get _name(): string;
    get _img(): string;
    get _class(): MonsterClass;
    get _level(): number;
    get _gene(): string;
    get _owner(): string;
    get _body(): MonsterBodyPart[];
    get _stats(): MonsterStats;
    get _children(): MonsterShortInfo[];
    get _parent(): MonsterShortInfo[];
    get _abilities(): MonsterAbility[];
    get _breed_count(): number;
    get _birth_day(): number;
    make_random_gene(length: number): string;
    get _info(): {
        id: string;
        name: string;
        img: string;
        owner: string;
        level: number;
        birth_day: number;
        value: number;
        gene: string;
        sale_info: SaleInfo;
        stats: MonsterStats;
        class: MonsterClass;
        abilities: MonsterAbility[];
        body: MonsterBodyPart[];
        children: MonsterShortInfo[];
        parent: MonsterShortInfo[];
        breed_count: number;
    };
}
