import { CoinUnit, TransactionType } from '../enums/type';
import { TransactionInfo } from '../typings';
import { Address } from '../utils/address';
declare class Transaction {
    private type;
    private from;
    private to;
    private value;
    private unit;
    private create_at;
    private data;
    private hash;
    private status;
    private block_id;
    private address;
    private gas;
    private gas_price;
    private payer;
    constructor(block_id: number, from: string, to: string, value: number, type: TransactionType, unit: CoinUnit, gas: number, gas_price: string, payer: string, data: any);
    get _type(): TransactionType;
    gen_hash(): string;
    get _payer(): Address;
    set _payer(payer: Address);
    get _address(): string;
    set _address(address: string);
    get _from(): string;
    get _to(): string;
    get _value(): number;
    get _unit(): CoinUnit;
    get _data(): string;
    get _hash(): string;
    get _create_at(): number;
    get _status(): string;
    get _block_id(): number;
    set _status(status: string);
    get _gas(): number;
    set _gas(gas: number);
    get _gas_price(): string;
    get _info(): TransactionInfo;
}
export default Transaction;
