"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Code = void 0;
var Code;
(function (Code) {
    Code[Code["success"] = 1] = "success";
    Code[Code["error"] = 0] = "error";
    Code[Code["not_found"] = -1] = "not_found";
    Code[Code["request_err"] = -2] = "request_err";
    Code[Code["err_private_key"] = -3] = "err_private_key";
    Code[Code["unknown"] = -4] = "unknown";
    Code[Code["error_block"] = -5] = "error_block";
    Code[Code["filter_err"] = -6] = "filter_err";
    Code[Code["hash_error"] = -7] = "hash_error";
    Code[Code["push_ql_error"] = -8] = "push_ql_error";
    Code[Code["push_arr_error"] = -9] = "push_arr_error";
    Code[Code["get_multi_error"] = -10] = "get_multi_error";
    Code[Code["txs_not_found"] = -11] = "txs_not_found";
    Code[Code["address_not_found"] = -12] = "address_not_found";
    Code[Code["full_node"] = -13] = "full_node";
})(Code || (Code = {}));
exports.Code = Code;
